# Generated by Django 4.2.2 on 2023-07-13 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_order_order_type'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order'),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('collecting', 'Collecting'), ('collected', 'Collected'), ('order_created', 'Order Created')], default='requested', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='pickup_date',
            field=models.DateField(),
        ),
    ]
