# Generated by Django 4.2.2 on 2023-07-14 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_pickuprequest_order_pickuprequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('collecting', 'Collecting'), ('collected', 'Collected'), ('order_created', 'Order Created'), ('cancelled', 'Cancelled')], default='requested', max_length=20, null=True),
        ),
    ]
