# Generated by Django 4.2.2 on 2023-07-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_pickuprequest_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='pickup_type',
            field=models.CharField(blank=True, choices=[('dropped', 'Dropped By User'), ('collected', 'Collected By Center')], default='collected', max_length=20, null=True),
        ),
    ]
