# Generated by Django 4.2.2 on 2023-07-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_collectioncenter_order_orderitem_order_clothes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='clothes',
            new_name='cloth',
        ),
    ]
