# Generated by Django 4.2.2 on 2023-07-05 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_clothes_orderitem_cloth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='clothes',
        ),
    ]
