# Generated by Django 4.2.3 on 2023-07-09 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_orderitem_cloth_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cloth',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cloth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cloth', to='base.clothes'),
            preserve_default=False,
        ),
    ]
