# Generated by Django 4.2.2 on 2023-07-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_invoice_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('walk-in', 'Walk-in'), ('subscription', 'Subscription')], default='walk-in', max_length=20, null=True),
        ),
    ]
