# Generated by Django 4.2.2 on 2023-07-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('collection_center', 'Collection Center'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
